<?php
/**
 * Created by PhpStorm.
 * User: fanzhaogui
 * Date: 2020/4/14
 * Time: 18:39
 */

namespace App\Process;


use EasySwoole\Component\Process\AbstractProcess;
use Swoole\Process;

class ProcessOne extends AbstractProcess
{
    // 当进程启动后，会执行的回调
    public function run($arg)
    {
        var_dump($this->getProcessName() . " :run\n");
        var_dump($arg);
    }


    public function onPipeReadable(Process $process)
    {
        parent::onPipeReadable($process); // TODO: Change the autogenerated stub
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
    }


    public function onException(\Throwable $throwable, ...$args)
    {
        parent::onException($throwable, $args); // TODO: Change the autogenerated stub
    }
}